<a href="https://colab.research.google.com/github/laxmibansal346/python-learning-labs/blob/main/Debugging_Exercise_on_Pandas_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Analytics Using Python
Module 3 – Debugging Exercise
Name: LAXMI BANSAL

Roll No: BETN1AI25226

**Q1. Error:**
Wrong function name (readcsv).

import pandas as pd

df = pd.readcsv('data.csv')

# **Correct Code:**

In [ ]:
import pandas as pd
df = pd.read_csv('dataset.csv')

df

      age    salary     income  gender       city    status  rating    price
0    11.0  68007.88   29435.41       F      Delhi   Unknown       6  2646.89
1    25.0  63995.24   87823.30    male      Delhi    Active       2  4642.47
2    44.0  44949.41   36788.47    Male      Delhi   Unknown       3  3194.65
3    39.0  29825.21   65812.03  Female  Bangalore    Active       4  3552.94
4    14.0  92077.45   53856.40       M      Delhi  Inactive       3  2425.69
..    ...       ...        ...     ...        ...       ...     ...      ...
351  42.0  52920.30   75667.84       M     Mumbai  Inactive       3  2114.04
352  32.0  75018.34   56680.28       M  Bangalore   Pending       7  2480.77
353  44.0  40779.68   58728.28  Female    Kolkata   Unknown       5   623.70
354   NaN  54484.90   47540.68       F     Mumbai   Unknown       2   460.13
355  29.0  71225.00  108334.61    male     Mumbai  Inactive       4  1895.66

[356 rows x 8 columns]

**Explanation:**
Correct function is read_csv() in pandas.

**Q2. DataFrame Creation Issue**

**Error:**
Incorrect dictionary syntax.

data = {'Name': ['Aman','Riya'], 'Age': 20, 21}

df = pd.DataFrame(data)

# correct code

In [ ]:

import pandas as pd

data = {'Name': ['Aman','Riya'], 'Age': [20, 21]}
df = pd.DataFrame(data)

print(df)

   Name  Age
0  Aman   20
1  Riya   21

**Explanation:**
Each key must have values in list format, but Age was not in list.

**Q3. Indexing Mistake**

**Error:**
Incomplete .loc[] syntax.

df = pd.read_csv('data.csv')

df.loc[1:5,'Salary'

In [ ]:
#Correct Code
import pandas as pd

df = pd.read_csv('dataset.csv')

df.loc[1:5, 'salary']

1    63995.24
2    44949.41
3    29825.21
4    92077.45
5    80107.82
Name: salary, dtype: float64

# **Explanation:**
 Closing bracket ] was missing in .loc[].

### **Q4. Filtering Error**

**Error:**
Incorrect condition syntax.

df[df['Salary' > 50000]]

In [ ]:
# Correct Code
import pandas as pd

df = pd.read_csv('dataset.csv')

df[df['salary'] > 50000]

      age    salary     income gender       city    status  rating    price
0    11.0  68007.88   29435.41      F      Delhi   Unknown       6  2646.89
1    25.0  63995.24   87823.30   male      Delhi    Active       2  4642.47
4    14.0  92077.45   53856.40      M      Delhi  Inactive       3  2425.69
5    58.0  80107.82  116896.94      F        NaN   Pending       3   596.96
7    58.0  54394.85   74403.02   Male    Kolkata    Active       6   622.31
..    ...       ...        ...    ...        ...       ...     ...      ...
349  42.0  72889.04   38003.60   male     Mumbai    Active       6  3370.99
351  42.0  52920.30   75667.84      M     Mumbai  Inactive       3  2114.04
352  32.0  75018.34   56680.28      M  Bangalore   Pending       7  2480.77
354   NaN  54484.90   47540.68      F     Mumbai   Unknown       2   460.13
355  29.0  71225.00  108334.61   male     Mumbai  Inactive       4  1895.66

[257 rows x 8 columns]

# **Explanation:**
Condition must be written outside column name with proper brackets.

# Q5. Group-by Syntax Error

 **Error:**
**Incorrect groupby syntax.**

df.groupby['Department'].mean()

In [ ]:
# Correct Code
import pandas as pd

df = pd.read_csv('dataset.csv')

df.groupby('Department').mean()

# Explanation:
groupby uses parentheses ( ) to call the function, not square brackets [ ].


# Q6. Missing Function Call

Error:
Function not called properly.

df.drop_duplicates

In [ ]:
# Correct Code
import pandas as pd

df = pd.read_csv('dataset.csv')

df.drop_duplicates()

      age    salary     income  gender       city    status  rating    price
0    11.0  68007.88   29435.41       F      Delhi   Unknown       6  2646.89
1    25.0  63995.24   87823.30    male      Delhi    Active       2  4642.47
2    44.0  44949.41   36788.47    Male      Delhi   Unknown       3  3194.65
3    39.0  29825.21   65812.03  Female  Bangalore    Active       4  3552.94
4    14.0  92077.45   53856.40       M      Delhi  Inactive       3  2425.69
..    ...       ...        ...     ...        ...       ...     ...      ...
351  42.0  52920.30   75667.84       M     Mumbai  Inactive       3  2114.04
352  32.0  75018.34   56680.28       M  Bangalore   Pending       7  2480.77
353  44.0  40779.68   58728.28  Female    Kolkata   Unknown       5   623.70
354   NaN  54484.90   47540.68       F     Mumbai   Unknown       2   460.13
355  29.0  71225.00  108334.61    male     Mumbai  Inactive       4  1895.66

[348 rows x 8 columns]


# Explanation:
Parentheses () are required to call the function.